version: 0.2

phases:
  pre_build:
    commands:
      - service docker start
      - echo Logging in to Amazon ECR...
      - echo | aws --version
      - echo | docker --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION | sed -e 's/-e none//g')
  build:
    commands:
      - pwd
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG